# podman build -t localhost/toolbox:44 .

FROM registry.fedoraproject.org/fedora-toolbox:44

# Disable h264 repo
RUN sed -i -e "s,enabled=1,enabled=0,g" /etc/yum.repos.d/fedora-cisco-openh264.repo

# Update base packages
#RUN dnf -y upgrade

# Install packages
# - jq, openssl for kind.sh
# - podman only for podman-completion
# - python3-pyyaml for release
#  bats \
#  p7zip \
#  podman \
RUN dnf install -y \
    @development-tools \
    awscli2 \
    cliphist \
    docker-compose \
    fzf \
    gh \
    gitleaks \
    helm \
    jq \
    oathtool \
    openssl \
    pass \
    perf \
    pinentry-gnome3 \
    podman-remote \
    python3-pyyaml \
    shellcheck \
    tealdeer \
    telnet \
    tmate \
    trash-cli \
    wdisplays \
    wl-mirror \
    xev \
    yq \
    --exclude=glib-networking \
    --exclude=logrotate \
    --exclude=low-memory-monitor \
    --exclude=mlocate \
    --exclude=nodejs-docs \
    --exclude=pipewire \
    --exclude=podman \
    --exclude=upower \
    --exclude=xdg-desktop-portal \
    --exclude=xdg-desktop-portal-gtk

# Remove packages
RUN dnf -y remove \
    glib-networking \
    logrotate \
    low-memory-monitor \
    mlocate \
    nodejs-docs \
    pipewire \
    podman \
    upower \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk

# Google Cloud CLI
# https://docs.cloud.google.com/sdk/docs/install-sdk#rpm
RUN tee /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-cli]
name=Google Cloud CLI
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el10-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key-v10.gpg
EOM
RUN CLOUDSDK_SKIP_PY_COMPILATION=1 dnf install -y \
    google-cloud-cli \
    libxcrypt-compat.x86_64

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf

RUN echo "toolbox create -i localhost/toolbox:44 fedora-toolbox-44"
RUN echo "toolbox enter"

